
package DotNetStub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceTCF", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceTCF {


    /**
     * 
     * @param passward
     * @param login
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/createAccount")
    @WebResult(name = "createAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.CreateAccountResponse")
    public String createAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "passward", targetNamespace = "http://tempuri.org/")
        String passward,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);

    /**
     * 
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/deleteAccount")
    @WebResult(name = "deleteAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "deleteAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.DeleteAccount")
    @ResponseWrapper(localName = "deleteAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.DeleteAccountResponse")
    public String deleteAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login);

    /**
     * 
     * @param passward
     * @param login
     * @param type
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/updateAccount")
    @WebResult(name = "updateAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.UpdateAccount")
    @ResponseWrapper(localName = "updateAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.UpdateAccountResponse")
    public String updateAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "passward", targetNamespace = "http://tempuri.org/")
        String passward,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        String type);

    /**
     * 
     * @param passward
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/loginAccount")
    @WebResult(name = "loginAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "loginAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.LoginAccount")
    @ResponseWrapper(localName = "loginAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.LoginAccountResponse")
    public String loginAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "passward", targetNamespace = "http://tempuri.org/")
        String passward);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/getListAccount")
    @WebResult(name = "getListAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getListAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListAccount")
    @ResponseWrapper(localName = "getListAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListAccountResponse")
    public String getListAccount();

    /**
     * 
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/getListInfoAccount")
    @WebResult(name = "getListInfoAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getListInfoAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListInfoAccount")
    @ResponseWrapper(localName = "getListInfoAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListInfoAccountResponse")
    public String getListInfoAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login);

    /**
     * 
     * @param address
     * @param numero
     * @param cry
     * @param login
     * @param exp
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/addInfoAccount")
    @WebResult(name = "addInfoAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addInfoAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.AddInfoAccount")
    @ResponseWrapper(localName = "addInfoAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.AddInfoAccountResponse")
    public String addInfoAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "nom", targetNamespace = "http://tempuri.org/")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "http://tempuri.org/")
        String prenom,
        @WebParam(name = "numero", targetNamespace = "http://tempuri.org/")
        Integer numero,
        @WebParam(name = "address", targetNamespace = "http://tempuri.org/")
        String address,
        @WebParam(name = "exp", targetNamespace = "http://tempuri.org/")
        String exp,
        @WebParam(name = "cry", targetNamespace = "http://tempuri.org/")
        Integer cry);

    /**
     * 
     * @param numero
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/deleteInfoAccount")
    @WebResult(name = "deleteInfoAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "deleteInfoAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.DeleteInfoAccount")
    @ResponseWrapper(localName = "deleteInfoAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.DeleteInfoAccountResponse")
    public String deleteInfoAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "numero", targetNamespace = "http://tempuri.org/")
        Integer numero);

    /**
     * 
     * @param address
     * @param numero
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/updateInfoAccount")
    @WebResult(name = "updateInfoAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateInfoAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.UpdateInfoAccount")
    @ResponseWrapper(localName = "updateInfoAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.UpdateInfoAccountResponse")
    public String updateInfoAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "numero", targetNamespace = "http://tempuri.org/")
        Integer numero,
        @WebParam(name = "address", targetNamespace = "http://tempuri.org/")
        String address);

    /**
     * 
     * @param numero
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/getInfoAccount")
    @WebResult(name = "getInfoAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getInfoAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetInfoAccount")
    @ResponseWrapper(localName = "getInfoAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetInfoAccountResponse")
    public String getInfoAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "numero", targetNamespace = "http://tempuri.org/")
        Integer numero);

    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/getRoles")
    @WebResult(name = "getRolesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetRoles")
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetRolesResponse")
    public String getRoles(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param username
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/getID")
    @WebResult(name = "getIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getID", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetID")
    @ResponseWrapper(localName = "getIDResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetIDResponse")
    public Integer getID(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/getListHistorique")
    @WebResult(name = "getListHistoriqueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getListHistorique", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListHistorique")
    @ResponseWrapper(localName = "getListHistoriqueResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListHistoriqueResponse")
    public String getListHistorique();

    /**
     * 
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/getListHistoriqueUser")
    @WebResult(name = "getListHistoriqueUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getListHistoriqueUser", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListHistoriqueUser")
    @ResponseWrapper(localName = "getListHistoriqueUserResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.GetListHistoriqueUserResponse")
    public String getListHistoriqueUser(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login);

    /**
     * 
     * @param recette
     * @param boutique
     * @param time
     * @param login
     * @param commande
     * @param quantite
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/addHistAccount")
    @WebResult(name = "addHistAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "addHistAccount", targetNamespace = "http://tempuri.org/", className = "DotNetStub.AddHistAccount")
    @ResponseWrapper(localName = "addHistAccountResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.AddHistAccountResponse")
    public String addHistAccount(
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "commande", targetNamespace = "http://tempuri.org/")
        Integer commande,
        @WebParam(name = "boutique", targetNamespace = "http://tempuri.org/")
        String boutique,
        @WebParam(name = "recette", targetNamespace = "http://tempuri.org/")
        String recette,
        @WebParam(name = "quantite", targetNamespace = "http://tempuri.org/")
        Integer quantite,
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/")
        String time);

    /**
     * 
     * @param number
     * @param role
     * @param prix
     * @param cry
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/IServiceTCF/payment")
    @WebResult(name = "paymentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "payment", targetNamespace = "http://tempuri.org/", className = "DotNetStub.Payment")
    @ResponseWrapper(localName = "paymentResponse", targetNamespace = "http://tempuri.org/", className = "DotNetStub.PaymentResponse")
    public String payment(
        @WebParam(name = "role", targetNamespace = "http://tempuri.org/")
        String role,
        @WebParam(name = "login", targetNamespace = "http://tempuri.org/")
        String login,
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        Integer number,
        @WebParam(name = "cry", targetNamespace = "http://tempuri.org/")
        Integer cry,
        @WebParam(name = "prix", targetNamespace = "http://tempuri.org/")
        Double prix);

}
