
package DotNetStub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceTCF", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:6606/ServiceTCF.svc?wsdl")
public class ServiceTCF
    extends Service
{

    private final static URL SERVICETCF_WSDL_LOCATION;
    private final static WebServiceException SERVICETCF_EXCEPTION;
    private final static QName SERVICETCF_QNAME = new QName("http://tempuri.org/", "ServiceTCF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6606/ServiceTCF.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICETCF_WSDL_LOCATION = url;
        SERVICETCF_EXCEPTION = e;
    }

    public ServiceTCF() {
        super(__getWsdlLocation(), SERVICETCF_QNAME);
    }

    public ServiceTCF(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICETCF_QNAME, features);
    }

    public ServiceTCF(URL wsdlLocation) {
        super(wsdlLocation, SERVICETCF_QNAME);
    }

    public ServiceTCF(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICETCF_QNAME, features);
    }

    public ServiceTCF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTCF(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceTCF
     */
    @WebEndpoint(name = "BasicHttpBinding_IServiceTCF")
    public IServiceTCF getBasicHttpBindingIServiceTCF() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServiceTCF"), IServiceTCF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceTCF
     */
    @WebEndpoint(name = "BasicHttpBinding_IServiceTCF")
    public IServiceTCF getBasicHttpBindingIServiceTCF(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IServiceTCF"), IServiceTCF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICETCF_EXCEPTION!= null) {
            throw SERVICETCF_EXCEPTION;
        }
        return SERVICETCF_WSDL_LOCATION;
    }

}
