//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public int id { get; set; }
        public int commande { get; set; }
        public float prix { get; set; }
        public string time { get; set; }
        public int id_utilisateur { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
