//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infomation
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public int numero { get; set; }
        public string adress { get; set; }
        public string expiration { get; set; }
        public int cryptogramme { get; set; }
        public int id_Utilisateur { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
