
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientAvecCompteServiceImplService", targetNamespace = "http://www.polytech.unice.fr/ClientAvecCompte", wsdlLocation = "http://localhost:8080/demo/webservices/ClientAvecCompteServiceImpl?wsdl")
public class ClientAvecCompteServiceImplService
    extends Service
{

    private final static URL CLIENTAVECCOMPTESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTAVECCOMPTESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTAVECCOMPTESERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/ClientAvecCompte", "ClientAvecCompteServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/demo/webservices/ClientAvecCompteServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTAVECCOMPTESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTAVECCOMPTESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ClientAvecCompteServiceImplService() {
        super(__getWsdlLocation(), CLIENTAVECCOMPTESERVICEIMPLSERVICE_QNAME);
    }

    public ClientAvecCompteServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTAVECCOMPTESERVICEIMPLSERVICE_QNAME, features);
    }

    public ClientAvecCompteServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTAVECCOMPTESERVICEIMPLSERVICE_QNAME);
    }

    public ClientAvecCompteServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTAVECCOMPTESERVICEIMPLSERVICE_QNAME, features);
    }

    public ClientAvecCompteServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientAvecCompteServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientAvecCompteService
     */
    @WebEndpoint(name = "ClientAvecCompteServiceImplPort")
    public ClientAvecCompteService getClientAvecCompteServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/ClientAvecCompte", "ClientAvecCompteServiceImplPort"), ClientAvecCompteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientAvecCompteService
     */
    @WebEndpoint(name = "ClientAvecCompteServiceImplPort")
    public ClientAvecCompteService getClientAvecCompteServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/ClientAvecCompte", "ClientAvecCompteServiceImplPort"), ClientAvecCompteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTAVECCOMPTESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTAVECCOMPTESERVICEIMPLSERVICE_EXCEPTION;
        }
        return CLIENTAVECCOMPTESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
