
package stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientAvecCompteService", targetNamespace = "http://webService.demo.se.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientAvecCompteService {


    /**
     * 
     * @param compteId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "recettePrefere", targetNamespace = "")
    @RequestWrapper(localName = "getRecettePrefere", targetNamespace = "http://webService.demo.se.polytech.unice.fr/", className = "stub.GetRecettePrefere")
    @ResponseWrapper(localName = "getRecettePrefereResponse", targetNamespace = "http://webService.demo.se.polytech.unice.fr/", className = "stub.GetRecettePrefereResponse")
    public String getRecettePrefere(
        @WebParam(name = "compteId", targetNamespace = "")
        int compteId);

    /**
     * 
     * @param compteId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "boutiquePrefere", targetNamespace = "")
    @RequestWrapper(localName = "getBoutiquePrefere", targetNamespace = "http://webService.demo.se.polytech.unice.fr/", className = "stub.GetBoutiquePrefere")
    @ResponseWrapper(localName = "getBoutiquePrefereResponse", targetNamespace = "http://webService.demo.se.polytech.unice.fr/", className = "stub.GetBoutiquePrefereResponse")
    public String getBoutiquePrefere(
        @WebParam(name = "compteId", targetNamespace = "")
        int compteId);

}
