<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.polytech.unice.fr/ClientAvecCompte" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://webService.demo.se.polytech.unice.fr/" name="ClientAvecCompteServiceImplService" targetNamespace="http://www.polytech.unice.fr/ClientAvecCompte">
  <wsdl:import location="http://localhost:8080/demo/webservices/ClientAvecCompteServiceImpl?wsdl=ClientAvecCompteService.wsdl" namespace="http://webService.demo.se.polytech.unice.fr/">
    </wsdl:import>
  <wsdl:binding name="ClientAvecCompteServiceImplServiceSoapBinding" type="ns1:ClientAvecCompteService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getRecettePrefere">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getRecettePrefere">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getRecettePrefereResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getBoutiquePrefere">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getBoutiquePrefere">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getBoutiquePrefereResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ClientAvecCompteServiceImplService">
    <wsdl:port binding="tns:ClientAvecCompteServiceImplServiceSoapBinding" name="ClientAvecCompteServiceImplPort">
      <soap:address location="http://localhost:8080/demo/webservices/ClientAvecCompteServiceImpl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>