
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResponsableTCFServiceImplService", targetNamespace = "http://www.polytech.unice.fr/Responsabletcf", wsdlLocation = "http://localhost:8080/demo/webservices/ResponsableTCFServiceImpl?wsdl")
public class ResponsableTCFServiceImplService
    extends Service
{

    private final static URL RESPONSABLETCFSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESPONSABLETCFSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RESPONSABLETCFSERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/Responsabletcf", "ResponsableTCFServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/demo/webservices/ResponsableTCFServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESPONSABLETCFSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RESPONSABLETCFSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ResponsableTCFServiceImplService() {
        super(__getWsdlLocation(), RESPONSABLETCFSERVICEIMPLSERVICE_QNAME);
    }

    public ResponsableTCFServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESPONSABLETCFSERVICEIMPLSERVICE_QNAME, features);
    }

    public ResponsableTCFServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RESPONSABLETCFSERVICEIMPLSERVICE_QNAME);
    }

    public ResponsableTCFServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESPONSABLETCFSERVICEIMPLSERVICE_QNAME, features);
    }

    public ResponsableTCFServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResponsableTCFServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResponsableTCFService
     */
    @WebEndpoint(name = "ResponsableTCFServiceImplPort")
    public ResponsableTCFService getResponsableTCFServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/Responsabletcf", "ResponsableTCFServiceImplPort"), ResponsableTCFService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResponsableTCFService
     */
    @WebEndpoint(name = "ResponsableTCFServiceImplPort")
    public ResponsableTCFService getResponsableTCFServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/Responsabletcf", "ResponsableTCFServiceImplPort"), ResponsableTCFService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESPONSABLETCFSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RESPONSABLETCFSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RESPONSABLETCFSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
