
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResponsableBoutiqueServiceImplService", targetNamespace = "http://www.polytech.unice.fr/ResponsableBoutique", wsdlLocation = "http://localhost:8080/demo/webservices/ResponsableBoutiqueServiceImpl?wsdl")
public class ResponsableBoutiqueServiceImplService
    extends Service
{

    private final static URL RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/ResponsableBoutique", "ResponsableBoutiqueServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/demo/webservices/ResponsableBoutiqueServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ResponsableBoutiqueServiceImplService() {
        super(__getWsdlLocation(), RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_QNAME);
    }

    public ResponsableBoutiqueServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_QNAME, features);
    }

    public ResponsableBoutiqueServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_QNAME);
    }

    public ResponsableBoutiqueServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_QNAME, features);
    }

    public ResponsableBoutiqueServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResponsableBoutiqueServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResponsableBoutiqueService
     */
    @WebEndpoint(name = "ResponsableBoutiqueServiceImplPort")
    public ResponsableBoutiqueService getResponsableBoutiqueServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/ResponsableBoutique", "ResponsableBoutiqueServiceImplPort"), ResponsableBoutiqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResponsableBoutiqueService
     */
    @WebEndpoint(name = "ResponsableBoutiqueServiceImplPort")
    public ResponsableBoutiqueService getResponsableBoutiqueServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/ResponsableBoutique", "ResponsableBoutiqueServiceImplPort"), ResponsableBoutiqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_EXCEPTION;
        }
        return RESPONSABLEBOUTIQUESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
