
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TcfServiceImplService", targetNamespace = "http://www.polytech.unice.fr/tcf", wsdlLocation = "http://localhost:8080/demo/webservices/TcfServiceImpl?wsdl")
public class TcfServiceImplService
    extends Service
{

    private final static URL TCFSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TCFSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TCFSERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/tcf", "TcfServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/demo/webservices/TcfServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TCFSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TCFSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TcfServiceImplService() {
        super(__getWsdlLocation(), TCFSERVICEIMPLSERVICE_QNAME);
    }

    public TcfServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TCFSERVICEIMPLSERVICE_QNAME, features);
    }

    public TcfServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TCFSERVICEIMPLSERVICE_QNAME);
    }

    public TcfServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TCFSERVICEIMPLSERVICE_QNAME, features);
    }

    public TcfServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TcfServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TcfService
     */
    @WebEndpoint(name = "TcfServiceImplPort")
    public TcfService getTcfServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/tcf", "TcfServiceImplPort"), TcfService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TcfService
     */
    @WebEndpoint(name = "TcfServiceImplPort")
    public TcfService getTcfServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/tcf", "TcfServiceImplPort"), TcfService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TCFSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TCFSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TCFSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
