//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.ServiceTCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTCF.IServiceTCF")]
    public interface IServiceTCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/createAccount", ReplyAction="http://tempuri.org/IServiceTCF/createAccountResponse")]
        string createAccount(string login, string passward, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/deleteAccount", ReplyAction="http://tempuri.org/IServiceTCF/deleteAccountResponse")]
        string deleteAccount(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/updateAccount", ReplyAction="http://tempuri.org/IServiceTCF/updateAccountResponse")]
        string updateAccount(string login, string passward, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/loginAccount", ReplyAction="http://tempuri.org/IServiceTCF/loginAccountResponse")]
        string loginAccount(string login, string passward);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/getListAccount", ReplyAction="http://tempuri.org/IServiceTCF/getListAccountResponse")]
        string getListAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/getListInfoAccount", ReplyAction="http://tempuri.org/IServiceTCF/getListInfoAccountResponse")]
        string getListInfoAccount(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/addInfoAccount", ReplyAction="http://tempuri.org/IServiceTCF/addInfoAccountResponse")]
        string addInfoAccount(string login, string nom, string prenom, int numero, string address, string exp, int cry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/deleteInfoAccount", ReplyAction="http://tempuri.org/IServiceTCF/deleteInfoAccountResponse")]
        string deleteInfoAccount(string login, int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/updateInfoAccount", ReplyAction="http://tempuri.org/IServiceTCF/updateInfoAccountResponse")]
        string updateInfoAccount(string login, int numero, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTCF/getInfoAccount", ReplyAction="http://tempuri.org/IServiceTCF/getInfoAccountResponse")]
        string getInfoAccount(string login, int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTCFChannel : TestClient.ServiceTCF.IServiceTCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTCFClient : System.ServiceModel.ClientBase<TestClient.ServiceTCF.IServiceTCF>, TestClient.ServiceTCF.IServiceTCF {
        
        public ServiceTCFClient() {
        }
        
        public ServiceTCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string createAccount(string login, string passward, string type) {
            return base.Channel.createAccount(login, passward, type);
        }
        
        public string deleteAccount(string login) {
            return base.Channel.deleteAccount(login);
        }
        
        public string updateAccount(string login, string passward, string type) {
            return base.Channel.updateAccount(login, passward, type);
        }
        
        public string loginAccount(string login, string passward) {
            return base.Channel.loginAccount(login, passward);
        }
        
        public string getListAccount() {
            return base.Channel.getListAccount();
        }
        
        public string getListInfoAccount(string login) {
            return base.Channel.getListInfoAccount(login);
        }
        
        public string addInfoAccount(string login, string nom, string prenom, int numero, string address, string exp, int cry) {
            return base.Channel.addInfoAccount(login, nom, prenom, numero, address, exp, cry);
        }
        
        public string deleteInfoAccount(string login, int numero) {
            return base.Channel.deleteInfoAccount(login, numero);
        }
        
        public string updateInfoAccount(string login, int numero, string address) {
            return base.Channel.updateInfoAccount(login, numero, address);
        }
        
        public string getInfoAccount(string login, int numero) {
            return base.Channel.getInfoAccount(login, numero);
        }
    }
}
